### PR TITLE
add logrotate boolean options: delaycompress, copy, copytruncate

### PR DESCRIPTION
**Pull request by andrewroffey**
---
name: Pull request
about: Add delaycompress, copy, copytruncate boolean options to logrotate config

---

delaycompress. copy and copytruncate are commonly used options/flags in logrotate configs. This PR adds these three boolean options.

### CODE REVIEW

**Comment by walbertus** [comment]
I think you need to add `copy`, `copytruncate` and `delaycompress` in file `/molecule/default/converge.yml`
Would love to see this PR merged

**Comment by andrewroffey** [comment]
Good point - I've just updated my PR with those tests

**Comment by andrewroffey** [comment]
Hi Robert, good point, I am looking over the tests now.

**Comment by andrewroffey** [comment]
@robertdebock I made a few changes and tests all green now

**Pull request merged**
